{% set name = "frilouz" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba7922f36500f6ea4a68e87f9cd24fe4a011a98673cb7ab4c7c3efcd33647a59

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - frilouz

about:
  home: https://github.com/serge-sans-paille/frilouz.git
  license_family: BSD
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A tiny wrapper compatible with "ast.parse" from the builtin "ast" module and "gast.parse" from the great "gast" package.
  description: |
    This package provides a single function "frilouz.parse", which returns
    a tuple of two elements, the parsed tree and a (possibly empty) list
    of Syntax errors during parsing.
  doc_url: https://github.com/serge-sans-paille/frilouz
  dev_url: https://github.com/serge-sans-paille/frilouz

extra:
  recipe-maintainers:
    - SylvainCorlay
    - marimeireles
